export const PERMISSIONS = [
  "user.create",
  "user.update",
  "user.disable",
  "user.delete",
  "user.reset_password",
  "role.manage",
  "datasource.create",
  "datasource.update",
  "datasource.delete",
  "datasource.preview",
  "datasource.refresh",
  "datasource.grant",
  "excel.upload",
  "excel.replace",
  "dashboard.create",
  "dashboard.update",
  "dashboard.delete",
  "dashboard.publish",
  "dashboard.view",
  "dashboard.export",
  "copilot.use",
  "audit.view",
  "audit.export",
  "login_history.view",
  "login_history.export",
  "organization.manage",
  "project.manage",
  "provider.manage",
  "privacy.manage",
  "system.health.view",
  "system.retention.manage",
  "bot.manage",
  "bot.use",
  "knowledge.manage",
  "knowledge.view",
  "legacy_api.manage",
  "legacy_api.use",
  "chat.use",
  "chat.audit",
  "insight.manage",
  "insight.view",
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

export const SYSTEM_ROLES: Record<
  string,
  { name: string; description: string; permissions: readonly PermissionKey[] }
> = {
  ADMIN: {
    name: "Admin",
    description: "InsightKM tenant administration with full access.",
    permissions: PERMISSIONS,
  },
  MANAGER: {
    name: "Manager",
    description: "Manages knowledge, bots, projects, and business insights.",
    permissions: [
      "datasource.create",
      "datasource.update",
      "datasource.preview",
      "datasource.refresh",
      "datasource.grant",
      "excel.upload",
      "excel.replace",
      "dashboard.create",
      "dashboard.update",
      "dashboard.publish",
      "dashboard.view",
      "dashboard.export",
      "copilot.use",
      "project.manage",
      "bot.manage",
      "bot.use",
      "knowledge.manage",
      "knowledge.view",
      "legacy_api.manage",
      "legacy_api.use",
      "chat.use",
      "chat.audit",
      "insight.manage",
      "insight.view",
    ],
  },
  USER: {
    name: "User",
    description: "Uses assigned knowledge, bots, chats, and insights.",
    permissions: [
      "datasource.preview",
      "dashboard.view",
      "copilot.use",
      "bot.use",
      "knowledge.view",
      "legacy_api.use",
      "chat.use",
      "insight.view",
    ],
  },
  SYSTEM_ADMIN: {
    name: "System Admin",
    description: "Full tenant administration and product access.",
    permissions: PERMISSIONS,
  },
  DATA_SOURCE_MANAGER: {
    name: "Data Source Manager",
    description: "Manages governed database and Excel data sources.",
    permissions: [
      "datasource.create",
      "datasource.update",
      "datasource.delete",
      "datasource.preview",
      "datasource.refresh",
      "datasource.grant",
      "excel.upload",
      "excel.replace",
      "dashboard.view",
    ],
  },
  DASHBOARD_BUILDER: {
    name: "Dashboard Builder",
    description: "Builds and publishes dashboards from assigned sources.",
    permissions: [
      "datasource.preview",
      "dashboard.create",
      "dashboard.update",
      "dashboard.delete",
      "dashboard.publish",
      "dashboard.view",
      "copilot.use",
    ],
  },
  DASHBOARD_VIEWER: {
    name: "Dashboard Viewer / AI Analyst",
    description: "Views assigned published dashboards and uses governed AI.",
    permissions: ["dashboard.view", "copilot.use"],
  },
};

// Compatibility bridge for organizations created before flexible RBAC existed.
// New authorization checks still use permission keys; legacy enum names are
// translated only here and can be removed after all memberships are migrated.
export const LEGACY_ROLE_PERMISSIONS: Record<string, readonly PermissionKey[]> =
  {
    OWNER: PERMISSIONS,
    ADMIN: PERMISSIONS,
    DASHBOARD_DESIGNER: [
      "datasource.preview",
      "dashboard.create",
      "dashboard.update",
      "dashboard.delete",
      "dashboard.publish",
      "dashboard.view",
      "copilot.use",
    ],
    ANALYST: ["dashboard.view", "dashboard.export", "copilot.use"],
    VIEWER: ["dashboard.view"],
  };
